[window]
width = 800
height = 800

[[pipeline]]
shader_type = "fragment"
label = "orb"
entry_point = "fs_main"
file = "fragment.wgsl"
persistent = true

[midi]
enabled = true

[hot_reload]
enabled = true